### ISSUE TITLE
Original MP3

### ISSUE THREAD

**Issue by joshkyh** [Earnings-Call-Dataset/MAEC-A-Multimodal-Aligned-Earnings-Conference-Call-Dataset-for-Financial-Risk-Prediction#1]
Dear Authors,

I was wondering if the original, raw mp3s are available along with the transcripts. I saw that the mp3s are processed into numeric matrices, say MFCC. I am hoping to get speaker-segmented mp3s ant not the numeric matrics, is that possible with this repo?

Thank you.

Best Regards,
Joshua

**Comment by Earnings-Call-Dataset** [comment]
Hi Joshua,

Thanks for your interest in our publication! Do you mind dropping me an email to my email address, please? Since Github has a limitation on repo size, I couldn't upload all files here.

Thank you

Kind regards,
Jiazheng

**Comment by joshkyh** [comment]
Done! Just sent an email to your ucdconnect.ie email address. Thanks again, Jiazheng. :)

**Comment by priolap** [comment]
Dear authors @Earnings-Call-Dataset,
is it possible to have the original mp3s dataset? Thank you so much!
Paola

**Comment by lijiazheng99** [comment]
@priolap Could you send me an email, please? Thanks
Jiazheng

**Comment by priolap** [comment]
I replied to your email. Thank you!!
Paola

**Comment by lijiazheng99** [comment]
May I ask which email you are contacting, please? Since I didn't get any email.
Jiazheng

**Comment by firmai** [comment]
You send the original files to me a few months ago, I feel like there is the opportunity for a new research paper that automatically updates with the latest calls. How would this be done, do you have any ideas?

**Comment by priolap** [comment]
of course, here we are: ***@***.***

thank you!
Paola

Il giorno lun 11 apr 2022 alle ore 15:22 Jiazheng Li <
***@***.***> ha scritto:

**Comment by zhaomin1995** [comment]
Hi.

Could you also share the original mp3 files with me?

My email address is zhaominxiao@my.unt.edu.

Zhaomin

> @priolap Could you send me an email, please? Thanks Jiazheng
